export const SDL_HINT_ACCELEROMETER_AS_JOYSTICK =
  "SDL_ACCELEROMETER_AS_JOYSTICK";
export const SDL_HINT_ALLOW_ALT_TAB_WHILE_GRABBED =
  "SDL_ALLOW_ALT_TAB_WHILE_GRABBED";
export const SDL_HINT_ALLOW_TOPMOST = "SDL_ALLOW_TOPMOST";
export const SDL_HINT_ANDROID_APK_EXPANSION_MAIN_FILE_VERSION =
  "SDL_ANDROID_APK_EXPANSION_MAIN_FILE_VERSION";
export const SDL_HINT_ANDROID_APK_EXPANSION_PATCH_FILE_VERSION =
  "SDL_ANDROID_APK_EXPANSION_PATCH_FILE_VERSION";
export const SDL_HINT_ANDROID_BLOCK_ON_PAUSE = "SDL_ANDROID_BLOCK_ON_PAUSE";
export const SDL_HINT_ANDROID_BLOCK_ON_PAUSE_PAUSEAUDIO =
  "SDL_ANDROID_BLOCK_ON_PAUSE_PAUSEAUDIO";
export const SDL_HINT_ANDROID_TRAP_BACK_BUTTON = "SDL_ANDROID_TRAP_BACK_BUTTON";
export const SDL_HINT_APP_NAME = "SDL_APP_NAME";
export const SDL_HINT_APPLE_TV_CONTROLLER_UI_EVENTS =
  "SDL_APPLE_TV_CONTROLLER_UI_EVENTS";
export const SDL_HINT_APPLE_TV_REMOTE_ALLOW_ROTATION =
  "SDL_APPLE_TV_REMOTE_ALLOW_ROTATION";
export const SDL_HINT_AUDIO_CATEGORY = "SDL_AUDIO_CATEGORY";
export const SDL_HINT_AUDIO_DEVICE_APP_NAME = "SDL_AUDIO_DEVICE_APP_NAME";
export const SDL_HINT_AUDIO_DEVICE_STREAM_NAME = "SDL_AUDIO_DEVICE_STREAM_NAME";
export const SDL_HINT_AUDIO_DEVICE_STREAM_ROLE = "SDL_AUDIO_DEVICE_STREAM_ROLE";
export const SDL_HINT_AUDIO_RESAMPLING_MODE = "SDL_AUDIO_RESAMPLING_MODE";
export const SDL_HINT_AUTO_UPDATE_JOYSTICKS = "SDL_AUTO_UPDATE_JOYSTICKS";
export const SDL_HINT_AUTO_UPDATE_SENSORS = "SDL_AUTO_UPDATE_SENSORS";
export const SDL_HINT_BMP_SAVE_LEGACY_FORMAT = "SDL_BMP_SAVE_LEGACY_FORMAT";
export const SDL_HINT_DISPLAY_USABLE_BOUNDS = "SDL_DISPLAY_USABLE_BOUNDS";
export const SDL_HINT_EMSCRIPTEN_ASYNCIFY = "SDL_EMSCRIPTEN_ASYNCIFY";
export const SDL_HINT_EMSCRIPTEN_KEYBOARD_ELEMENT =
  "SDL_EMSCRIPTEN_KEYBOARD_ELEMENT";
export const SDL_HINT_ENABLE_STEAM_CONTROLLERS = "SDL_ENABLE_STEAM_CONTROLLERS";
export const SDL_HINT_EVENT_LOGGING = "SDL_EVENT_LOGGING";
export const SDL_HINT_FRAMEBUFFER_ACCELERATION = "SDL_FRAMEBUFFER_ACCELERATION";
export const SDL_HINT_GAMECONTROLLERCONFIG = "SDL_GAMECONTROLLERCONFIG";
export const SDL_HINT_GAMECONTROLLERCONFIG_FILE =
  "SDL_GAMECONTROLLERCONFIG_FILE";
export const SDL_HINT_GAMECONTROLLERTYPE = "SDL_GAMECONTROLLERTYPE";
export const SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES =
  "SDL_GAMECONTROLLER_IGNORE_DEVICES";
export const SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT =
  "SDL_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT";
export const SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS =
  "SDL_GAMECONTROLLER_USE_BUTTON_LABELS";
export const SDL_HINT_GRAB_KEYBOARD = "SDL_GRAB_KEYBOARD";
export const SDL_HINT_IDLE_TIMER_DISABLED = "SDL_IOS_IDLE_TIMER_DISABLED";
export const SDL_HINT_IME_INTERNAL_EDITING = "SDL_IME_INTERNAL_EDITING";
export const SDL_HINT_IME_SHOW_UI = "SDL_IME_SHOW_UI";
export const SDL_HINT_IOS_HIDE_HOME_INDICATOR = "SDL_IOS_HIDE_HOME_INDICATOR";
export const SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS =
  "SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS";
export const SDL_HINT_JOYSTICK_HIDAPI = "SDL_JOYSTICK_HIDAPI";
export const SDL_HINT_JOYSTICK_HIDAPI_GAMECUBE = "SDL_JOYSTICK_HIDAPI_GAMECUBE";
export const SDL_HINT_JOYSTICK_HIDAPI_JOY_CONS = "SDL_JOYSTICK_HIDAPI_JOY_CONS";
export const SDL_HINT_JOYSTICK_HIDAPI_LUNA = "SDL_JOYSTICK_HIDAPI_LUNA";
export const SDL_HINT_JOYSTICK_HIDAPI_PS4 = "SDL_JOYSTICK_HIDAPI_PS4";
export const SDL_HINT_JOYSTICK_HIDAPI_PS4_RUMBLE =
  "SDL_JOYSTICK_HIDAPI_PS4_RUMBLE";
export const SDL_HINT_JOYSTICK_HIDAPI_PS5 = "SDL_JOYSTICK_HIDAPI_PS5";
export const SDL_HINT_JOYSTICK_HIDAPI_PS5_PLAYER_LED =
  "SDL_JOYSTICK_HIDAPI_PS5_PLAYER_LED";
export const SDL_HINT_JOYSTICK_HIDAPI_PS5_RUMBLE =
  "SDL_JOYSTICK_HIDAPI_PS5_RUMBLE";
export const SDL_HINT_JOYSTICK_HIDAPI_STADIA = "SDL_JOYSTICK_HIDAPI_STADIA";
export const SDL_HINT_JOYSTICK_HIDAPI_STEAM = "SDL_JOYSTICK_HIDAPI_STEAM";
export const SDL_HINT_JOYSTICK_HIDAPI_SWITCH = "SDL_JOYSTICK_HIDAPI_SWITCH";
export const SDL_HINT_JOYSTICK_HIDAPI_SWITCH_HOME_LED =
  "SDL_JOYSTICK_HIDAPI_SWITCH_HOME_LED";
export const SDL_HINT_JOYSTICK_HIDAPI_XBOX = "SDL_JOYSTICK_HIDAPI_XBOX";
export const SDL_HINT_JOYSTICK_RAWINPUT = "SDL_JOYSTICK_RAWINPUT";
export const SDL_HINT_JOYSTICK_RAWINPUT_CORRELATE_XINPUT =
  "SDL_JOYSTICK_RAWINPUT_CORRELATE_XINPUT";
export const SDL_HINT_JOYSTICK_THREAD = "SDL_JOYSTICK_THREAD";
export const SDL_HINT_KMSDRM_REQUIRE_DRM_MASTER =
  "SDL_KMSDRM_REQUIRE_DRM_MASTER";
export const SDL_HINT_JOYSTICK_DEVICE = "SDL_JOYSTICK_DEVICE";
export const SDL_HINT_LINUX_JOYSTICK_CLASSIC = "SDL_LINUX_JOYSTICK_CLASSIC";
export const SDL_HINT_LINUX_JOYSTICK_DEADZONES = "SDL_LINUX_JOYSTICK_DEADZONES";
export const SDL_HINT_MAC_BACKGROUND_APP = "SDL_MAC_BACKGROUND_APP";
export const SDL_HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK =
  "SDL_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK";
export const SDL_HINT_MOUSE_DOUBLE_CLICK_RADIUS =
  "SDL_MOUSE_DOUBLE_CLICK_RADIUS";
export const SDL_HINT_MOUSE_DOUBLE_CLICK_TIME = "SDL_MOUSE_DOUBLE_CLICK_TIME";
export const SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH = "SDL_MOUSE_FOCUS_CLICKTHROUGH";
export const SDL_HINT_MOUSE_NORMAL_SPEED_SCALE = "SDL_MOUSE_NORMAL_SPEED_SCALE";
export const SDL_HINT_MOUSE_RELATIVE_MODE_WARP = "SDL_MOUSE_RELATIVE_MODE_WARP";
export const SDL_HINT_MOUSE_RELATIVE_SCALING = "SDL_MOUSE_RELATIVE_SCALING";
export const SDL_HINT_MOUSE_RELATIVE_SPEED_SCALE =
  "SDL_MOUSE_RELATIVE_SPEED_SCALE";
export const SDL_HINT_MOUSE_TOUCH_EVENTS = "SDL_MOUSE_TOUCH_EVENTS";
export const SDL_HINT_NO_SIGNAL_HANDLERS = "SDL_NO_SIGNAL_HANDLERS";
export const SDL_HINT_OPENGL_ES_DRIVER = "SDL_OPENGL_ES_DRIVER";
export const SDL_HINT_ORIENTATIONS = "SDL_IOS_ORIENTATIONS";
export const SDL_HINT_POLL_SENTINEL = "SDL_POLL_SENTINEL";
export const SDL_HINT_PREFERRED_LOCALES = "SDL_PREFERRED_LOCALES";
export const SDL_HINT_QTWAYLAND_CONTENT_ORIENTATION =
  "SDL_QTWAYLAND_CONTENT_ORIENTATION";
export const SDL_HINT_QTWAYLAND_WINDOW_FLAGS = "SDL_QTWAYLAND_WINDOW_FLAGS";
export const SDL_HINT_RENDER_BATCHING = "SDL_RENDER_BATCHING";
export const SDL_HINT_RENDER_LINE_METHOD = "SDL_RENDER_LINE_METHOD";
export const SDL_HINT_RENDER_DIRECT3D11_DEBUG = "SDL_RENDER_DIRECT3D11_DEBUG";
export const SDL_HINT_RENDER_DIRECT3D_THREADSAFE =
  "SDL_RENDER_DIRECT3D_THREADSAFE";
export const SDL_HINT_RENDER_DRIVER = "SDL_RENDER_DRIVER";
export const SDL_HINT_RENDER_LOGICAL_SIZE_MODE = "SDL_RENDER_LOGICAL_SIZE_MODE";
export const SDL_HINT_RENDER_OPENGL_SHADERS = "SDL_RENDER_OPENGL_SHADERS";
export const SDL_HINT_RENDER_SCALE_QUALITY = "SDL_RENDER_SCALE_QUALITY";
export const SDL_HINT_RENDER_VSYNC = "SDL_RENDER_VSYNC";
export const SDL_HINT_RETURN_KEY_HIDES_IME = "SDL_RETURN_KEY_HIDES_IME";
export const SDL_HINT_RPI_VIDEO_LAYER = "SDL_RPI_VIDEO_LAYER";
export const SDL_HINT_SCREENSAVER_INHIBIT_ACTIVITY_NAME =
  "SDL_SCREENSAVER_INHIBIT_ACTIVITY_NAME";
export const SDL_HINT_THREAD_FORCE_REALTIME_TIME_CRITICAL =
  "SDL_THREAD_FORCE_REALTIME_TIME_CRITICAL";
export const SDL_HINT_THREAD_PRIORITY_POLICY = "SDL_THREAD_PRIORITY_POLICY";
export const SDL_HINT_THREAD_STACK_SIZE = "SDL_THREAD_STACK_SIZE";
export const SDL_HINT_TIMER_RESOLUTION = "SDL_TIMER_RESOLUTION";
export const SDL_HINT_TOUCH_MOUSE_EVENTS = "SDL_TOUCH_MOUSE_EVENTS";
export const SDL_HINT_TV_REMOTE_AS_JOYSTICK = "SDL_TV_REMOTE_AS_JOYSTICK";
export const SDL_HINT_VIDEO_ALLOW_SCREENSAVER = "SDL_VIDEO_ALLOW_SCREENSAVER";
export const SDL_HINT_VIDEO_DOUBLE_BUFFER = "SDL_VIDEO_DOUBLE_BUFFER";
export const SDL_HINT_VIDEO_EGL_ALLOW_TRANSPARENCY =
  "SDL_VIDEO_EGL_ALLOW_TRANSPARENCY";
export const SDL_HINT_VIDEO_EXTERNAL_CONTEXT = "SDL_VIDEO_EXTERNAL_CONTEXT";
export const SDL_HINT_VIDEO_HIGHDPI_DISABLED = "SDL_VIDEO_HIGHDPI_DISABLED";
export const SDL_HINT_VIDEO_MAC_FULLSCREEN_SPACES =
  "SDL_VIDEO_MAC_FULLSCREEN_SPACES";
export const SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS =
  "SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS";
export const SDL_HINT_VIDEO_WAYLAND_ALLOW_LIBDECOR =
  "SDL_VIDEO_WAYLAND_ALLOW_LIBDECOR";
export const SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT =
  "SDL_VIDEO_WINDOW_SHARE_PIXEL_FORMAT";
export const SDL_HINT_VIDEO_WIN_D3DCOMPILER = "SDL_VIDEO_WIN_D3DCOMPILER";
export const SDL_HINT_VIDEO_X11_FORCE_EGL = "SDL_VIDEO_X11_FORCE_EGL";
export const SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR =
  "SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR";
export const SDL_HINT_VIDEO_X11_NET_WM_PING = "SDL_VIDEO_X11_NET_WM_PING";
export const SDL_HINT_VIDEO_X11_WINDOW_VISUALID =
  "SDL_VIDEO_X11_WINDOW_VISUALID";
export const SDL_HINT_VIDEO_X11_XINERAMA = "SDL_VIDEO_X11_XINERAMA";
export const SDL_HINT_VIDEO_X11_XRANDR = "SDL_VIDEO_X11_XRANDR";
export const SDL_HINT_VIDEO_X11_XVIDMODE = "SDL_VIDEO_X11_XVIDMODE";
export const SDL_HINT_WAVE_FACT_CHUNK = "SDL_WAVE_FACT_CHUNK";
export const SDL_HINT_WAVE_RIFF_CHUNK_SIZE = "SDL_WAVE_RIFF_CHUNK_SIZE";
export const SDL_HINT_WAVE_TRUNCATION = "SDL_WAVE_TRUNCATION";
export const SDL_HINT_WINDOWS_DISABLE_THREAD_NAMING =
  "SDL_WINDOWS_DISABLE_THREAD_NAMING";
export const SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP =
  "SDL_WINDOWS_ENABLE_MESSAGELOOP";
export const SDL_HINT_WINDOWS_FORCE_MUTEX_CRITICAL_SECTIONS =
  "SDL_WINDOWS_FORCE_MUTEX_CRITICAL_SECTIONS";
export const SDL_HINT_WINDOWS_FORCE_SEMAPHORE_KERNEL =
  "SDL_WINDOWS_FORCE_SEMAPHORE_KERNEL";
export const SDL_HINT_WINDOWS_INTRESOURCE_ICON = "SDL_WINDOWS_INTRESOURCE_ICON";
export const SDL_HINT_WINDOWS_INTRESOURCE_ICON_SMALL =
  "SDL_WINDOWS_INTRESOURCE_ICON_SMALL";
export const SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4 =
  "SDL_WINDOWS_NO_CLOSE_ON_ALT_F4";
export const SDL_HINT_WINDOWS_USE_D3D9EX = "SDL_WINDOWS_USE_D3D9EX";
export const SDL_HINT_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN =
  "SDL_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN";
export const SDL_HINT_WINDOW_NO_ACTIVATION_WHEN_SHOWN =
  "SDL_WINDOW_NO_ACTIVATION_WHEN_SHOWN";
export const SDL_HINT_WINRT_HANDLE_BACK_BUTTON = "SDL_WINRT_HANDLE_BACK_BUTTON";
export const SDL_HINT_WINRT_PRIVACY_POLICY_LABEL =
  "SDL_WINRT_PRIVACY_POLICY_LABEL";
export const SDL_HINT_WINRT_PRIVACY_POLICY_URL = "SDL_WINRT_PRIVACY_POLICY_URL";
export const SDL_HINT_X11_FORCE_OVERRIDE_REDIRECT =
  "SDL_X11_FORCE_OVERRIDE_REDIRECT";
export const SDL_HINT_XINPUT_ENABLED = "SDL_XINPUT_ENABLED";
export const SDL_HINT_XINPUT_USE_OLD_JOYSTICK_MAPPING =
  "SDL_XINPUT_USE_OLD_JOYSTICK_MAPPING";
export const SDL_HINT_AUDIO_INCLUDE_MONITORS = "SDL_AUDIO_INCLUDE_MONITORS";
